name: Release

on:
  workflow_dispatch:
  
jobs:
  build-and-deploy:
    runs-on: windows-latest
    steps:

      # Checkout the repo
      - uses: actions/checkout@v4
      
      - name: Setup .NET Core
        uses: actions/setup-dotnet@v4
        with:
          dotnet-version: 8.0.x

      - name: Install dependencies
        run: dotnet restore BlazorGeophires/BlazorGeophires.csproj

      - name: Build
        run: dotnet build BlazorGeophires/BlazorGeophires.csproj --configuration Release --no-restore

      - name: Publish Blazor WebAssembly app
        run: dotnet publish BlazorGeophires/BlazorGeophires.csproj -c Release -o publish

      - name: Upload to Azure Blob Storage
        uses: azure/cli@v1
        with:
          inlineScript: |
            az storage blob upload-batch \
              --account-name ${{ secrets.AZURE_STORAGE_ACCOUNT }} \
              --destination '$web' \
              --source 'publish/wwwroot' \
              --overwrite
        env:
          AZURE_STORAGE_KEY: ${{ secrets.AZURE_STORAGE_KEY }}
