name: Release

on:
  workflow_dispatch:
  
jobs:
  build-and-deploy:
    runs-on: windows-latest
    steps:

      # Checkout the repo
      - uses: actions/checkout@v4
      
      - name: Setup .NET Core
        uses: actions/setup-dotnet@v4
        with:
          dotnet-version: 8.0.x

      - name: Install dependencies
        run: dotnet restore BlazorGeophiresSharp/server/BlazorGeophiresSharp.Server.csproj

      - name: Build
        run: dotnet build BlazorGeophiresSharp/server/BlazorGeophiresSharp.Server.csproj --configuration Release --no-restore

      - name: Publish
        run: dotnet publish BlazorGeophiresSharp/server/BlazorGeophiresSharp.Server.csproj

      - name: Create zip File
        run: |
          Compress-Archive -Path BlazorGeophiresSharp\server\bin\Release\net8.0\publish\* -DestinationPath app.zip -Force

      - name: Upload artifact
        uses: actions/upload-artifact@v4
        with:
          name: Release
          path: app.zip
