name: Release

on:
  workflow_dispatch:
  
jobs:
  build-and-deploy:
    runs-on: windows-latest
    steps:

      # Checkout the repo
      - uses: actions/checkout@v4
      
      - name: Setup .NET Core
        uses: actions/setup-dotnet@v4
        with:
          dotnet-version: 8.0.x

      - name: Install dependencies
        run: dotnet restore BlazorGeophires/BlazorGeophires.csproj

      - name: Build
        run: dotnet build BlazorGeophires/BlazorGeophires.csproj --configuration Release --no-restore

      #- name: Publish
      #  run: dotnet publish BlazorGeophires/BlazorGeophires.csproj

      - name: Publish
        run: dotnet publish BlazorGeophires/BlazorGeophires.csproj -o ${{ github.workspace }}/publish -c Release --no-restore --no-build

      - name: Upload Hosted Server Build Artifact
        uses: actions/upload-artifact@v4
        with:
          name: HostedServer
          path: ${{ github.workspace }}/publish

      #- name: Create zip File
      # run: |
      #    Compress-Archive -Path BlazorGeophires\bin\Release\net8.0\publish\* -DestinationPath app.zip -Force

      #- name: Upload artifact
      #  uses: actions/upload-artifact@v4
      #  with:
      #    name: Release
      #    path: app.zip
